package com.jyyx.dao.mysql.dao.extend;

import com.jyyx.dao.mysql.entity.Msg;
import com.jyyx.dao.mysql.entity.MsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgExtendMapper {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    List<Msg> selectByExample(MsgExample example);

}