package com.jyyx.dao.mysql.dao;

import com.jyyx.dao.mysql.entity.Case;
import com.jyyx.dao.mysql.entity.CaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    int countByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    int deleteByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    int insert(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    int insertSelective(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    List<Case> selectByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    Case selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Case record, @Param("example") CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Case record, @Param("example") CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_case
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Case record);
}