package com.jyyx.dao.mysql.dao;

import com.jyyx.dao.mysql.entity.MsgCategory;
import com.jyyx.dao.mysql.entity.MsgCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    int countByExample(MsgCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    int deleteByExample(MsgCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    int insert(MsgCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    int insertSelective(MsgCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    List<MsgCategory> selectByExample(MsgCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    MsgCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MsgCategory record, @Param("example") MsgCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MsgCategory record, @Param("example") MsgCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MsgCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MsgCategory record);
}