package com.jyyx.dao.mysql.dao;

import com.jyyx.dao.mysql.entity.Msg;
import com.jyyx.dao.mysql.entity.MsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int countByExample(MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int deleteByExample(MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int insert(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int insertSelective(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    List<Msg> selectByExampleWithBLOBs(MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    List<Msg> selectByExample(MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    Msg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Msg record, @Param("example") MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Msg record, @Param("example") MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Msg record, @Param("example") MsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Msg record);
}