package com.jyyx.dao.mysql.dao;

import com.jyyx.dao.mysql.entity.ProductCateRelation;
import com.jyyx.dao.mysql.entity.ProductCateRelationExample;
import com.jyyx.dao.mysql.entity.ProductCateRelationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductCateRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    int countByExample(ProductCateRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    int deleteByExample(ProductCateRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ProductCateRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    int insert(ProductCateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    int insertSelective(ProductCateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    List<ProductCateRelation> selectByExample(ProductCateRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    ProductCateRelation selectByPrimaryKey(ProductCateRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductCateRelation record, @Param("example") ProductCateRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductCateRelation record, @Param("example") ProductCateRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductCateRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jy_product_category_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductCateRelation record);
}