package com.jyyx.dao.mysql.entity;

public class CaseCateRelationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_case_category_relation.case_id
     *
     * @mbggenerated
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_case_category_relation.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_case_category_relation.case_id
     *
     * @return the value of jy_case_category_relation.case_id
     *
     * @mbggenerated
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_case_category_relation.case_id
     *
     * @param caseId the value for jy_case_category_relation.case_id
     *
     * @mbggenerated
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_case_category_relation.category_id
     *
     * @return the value of jy_case_category_relation.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_case_category_relation.category_id
     *
     * @param categoryId the value for jy_case_category_relation.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}