package com.jyyx.dao.mysql.entity;

import java.util.Date;

public class Case {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_case.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_case.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_case.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_case.case_name
     *
     * @mbggenerated
     */
    private String caseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_case.case_desc
     *
     * @mbggenerated
     */
    private String caseDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_case.case_price
     *
     * @mbggenerated
     */
    private Double casePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_case.case_tips
     *
     * @mbggenerated
     */
    private String caseTips;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_case.id
     *
     * @return the value of jy_case.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_case.id
     *
     * @param id the value for jy_case.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_case.create_time
     *
     * @return the value of jy_case.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_case.create_time
     *
     * @param createTime the value for jy_case.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_case.updated_time
     *
     * @return the value of jy_case.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_case.updated_time
     *
     * @param updatedTime the value for jy_case.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_case.case_name
     *
     * @return the value of jy_case.case_name
     *
     * @mbggenerated
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_case.case_name
     *
     * @param caseName the value for jy_case.case_name
     *
     * @mbggenerated
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_case.case_desc
     *
     * @return the value of jy_case.case_desc
     *
     * @mbggenerated
     */
    public String getCaseDesc() {
        return caseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_case.case_desc
     *
     * @param caseDesc the value for jy_case.case_desc
     *
     * @mbggenerated
     */
    public void setCaseDesc(String caseDesc) {
        this.caseDesc = caseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_case.case_price
     *
     * @return the value of jy_case.case_price
     *
     * @mbggenerated
     */
    public Double getCasePrice() {
        return casePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_case.case_price
     *
     * @param casePrice the value for jy_case.case_price
     *
     * @mbggenerated
     */
    public void setCasePrice(Double casePrice) {
        this.casePrice = casePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_case.case_tips
     *
     * @return the value of jy_case.case_tips
     *
     * @mbggenerated
     */
    public String getCaseTips() {
        return caseTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_case.case_tips
     *
     * @param caseTips the value for jy_case.case_tips
     *
     * @mbggenerated
     */
    public void setCaseTips(String caseTips) {
        this.caseTips = caseTips;
    }
}