package com.jyyx.dao.mysql.entity;

import java.util.Date;

public class Pic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_pic.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_pic.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_pic.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_pic.pic_length
     *
     * @mbggenerated
     */
    private Integer picLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_pic.pic_code
     *
     * @mbggenerated
     */
    private String picCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_pic.refer_id
     *
     * @mbggenerated
     */
    private Integer referId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_pic.order_code
     *
     * @mbggenerated
     */
    private Integer orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_pic.pic_path
     *
     * @mbggenerated
     */
    private String picPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_pic.Id
     *
     * @return the value of jy_pic.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_pic.Id
     *
     * @param id the value for jy_pic.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_pic.create_time
     *
     * @return the value of jy_pic.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_pic.create_time
     *
     * @param createTime the value for jy_pic.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_pic.updated_time
     *
     * @return the value of jy_pic.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_pic.updated_time
     *
     * @param updatedTime the value for jy_pic.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_pic.pic_length
     *
     * @return the value of jy_pic.pic_length
     *
     * @mbggenerated
     */
    public Integer getPicLength() {
        return picLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_pic.pic_length
     *
     * @param picLength the value for jy_pic.pic_length
     *
     * @mbggenerated
     */
    public void setPicLength(Integer picLength) {
        this.picLength = picLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_pic.pic_code
     *
     * @return the value of jy_pic.pic_code
     *
     * @mbggenerated
     */
    public String getPicCode() {
        return picCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_pic.pic_code
     *
     * @param picCode the value for jy_pic.pic_code
     *
     * @mbggenerated
     */
    public void setPicCode(String picCode) {
        this.picCode = picCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_pic.refer_id
     *
     * @return the value of jy_pic.refer_id
     *
     * @mbggenerated
     */
    public Integer getReferId() {
        return referId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_pic.refer_id
     *
     * @param referId the value for jy_pic.refer_id
     *
     * @mbggenerated
     */
    public void setReferId(Integer referId) {
        this.referId = referId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_pic.order_code
     *
     * @return the value of jy_pic.order_code
     *
     * @mbggenerated
     */
    public Integer getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_pic.order_code
     *
     * @param orderCode the value for jy_pic.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(Integer orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_pic.pic_path
     *
     * @return the value of jy_pic.pic_path
     *
     * @mbggenerated
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_pic.pic_path
     *
     * @param picPath the value for jy_pic.pic_path
     *
     * @mbggenerated
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }
}