package com.jyyx.dao.mysql.entity;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_product.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_product.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_product.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_product.product_link
     *
     * @mbggenerated
     */
    private String productLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_product.product_desc
     *
     * @mbggenerated
     */
    private String productDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_product.id
     *
     * @return the value of jy_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_product.id
     *
     * @param id the value for jy_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_product.create_time
     *
     * @return the value of jy_product.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_product.create_time
     *
     * @param createTime the value for jy_product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_product.updated_time
     *
     * @return the value of jy_product.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_product.updated_time
     *
     * @param updatedTime the value for jy_product.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_product.product_name
     *
     * @return the value of jy_product.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_product.product_name
     *
     * @param productName the value for jy_product.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_product.product_link
     *
     * @return the value of jy_product.product_link
     *
     * @mbggenerated
     */
    public String getProductLink() {
        return productLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_product.product_link
     *
     * @param productLink the value for jy_product.product_link
     *
     * @mbggenerated
     */
    public void setProductLink(String productLink) {
        this.productLink = productLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_product.product_desc
     *
     * @return the value of jy_product.product_desc
     *
     * @mbggenerated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_product.product_desc
     *
     * @param productDesc the value for jy_product.product_desc
     *
     * @mbggenerated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }
}