package com.jyyx.dao.mysql.entity;

public class ProductCateRelationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_product_category_relation.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jy_product_category_relation.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_product_category_relation.product_id
     *
     * @return the value of jy_product_category_relation.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_product_category_relation.product_id
     *
     * @param productId the value for jy_product_category_relation.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jy_product_category_relation.category_id
     *
     * @return the value of jy_product_category_relation.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jy_product_category_relation.category_id
     *
     * @param categoryId the value for jy_product_category_relation.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}